# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
        environment:
          FI1_BRIDGE_VERSION: v0.0.28
          FI2_BRIDGE_VERSION: master

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install

      # - setup_remote_docker:
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv -f /tmp/docker/* /usr/bin          
            systemctl start docker

      - run: ./script.sh

      