version: 2.1

commands: 
  starttest:
    steps:
      - checkout
      - run: npm install
      - run: ./script.sh
  checkenv:
    steps:
      - run: 
          name: "Check custom environment variables"
          command: |
            echo ${FI2_BRIDGE_VERSION}
            echo ${FI1_BRIDGE_VERSION} 

jobs:
  test_v18_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.18"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest
  test_v19_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.19"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest  
  test_v20_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.20"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest          
  test_v21_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.21"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest  
  test_v22_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.22"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest 
  test_v23_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.23"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest 
  test_v24_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.24"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest  
  test_v25_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.25"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest
  test_v26_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.26"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest 
  test_v27_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.27"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest                                   
  test_v28_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.28"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest
  test_v29_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.29"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest  
  test_v30_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.30"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest      
  test_v31_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.31"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest
  test_v32_v32:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
      - checkenv
      - starttest      
  test_v32rc_v32rc:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.32rc1"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32rc1"' >> $BASH_ENV
      - checkenv
      - starttest
  test_v31_v32rc:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.31"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="v0.0.32rc1"' >> $BASH_ENV
      - checkenv
      - starttest
  test_v32_master:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="v0.0.32"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="master"' >> $BASH_ENV
      - checkenv
      - starttest     
  test_master_master:
    machine: true
    working_directory: ~/repo
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export FI2_BRIDGE_VERSION="master"' >> $BASH_ENV
            echo 'export FI1_BRIDGE_VERSION="master"' >> $BASH_ENV
      - checkenv
      - starttest   
         

workflows:
  version: 2

  test_integration:
    jobs:
      - test_v18_v32
      - test_v19_v32:
          requires:
            - test_v18_v32
      - test_v20_v32:
          requires:
            - test_v19_v32
      - test_v21_v32:
          requires:
            - test_v20_v32            
      - test_v22_v32:
          requires:
            - test_v21_v32            
      - test_v23_v32:
          requires:
            - test_v22_v32            
      - test_v24_v32:
          requires:
            - test_v23_v32            
      - test_v25_v32:
          requires:
            - test_v24_v32            
      - test_v26_v32:
          requires:
            - test_v25_v32            
      - test_v27_v32:
          requires:
            - test_v26_v32            
      - test_v28_v32:
          requires:
            - test_v27_v32
      - test_v29_v32:
          requires:
            - test_v28_v32
      - test_v30_v32:
          requires:
            - test_v29_v32
      - test_v31_v32:
          requires:
            - test_v30_v32            
      - test_v32_v32:
          requires:
            - test_v31_v32            
      - test_v32rc_v32rc:
          requires:
            - test_v32_v32            
      - test_v31_v32rc:
          requires:
            - test_v32rc_v32rc
      - test_v32_master:
          requires:
            - test_v31_v32rc
      - test_master_master:
          requires:
            - test_v32_master



      