version: 2
jobs:
  build:
    docker:
      - image: golang:1.6.4-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:   
          docker_layer_caching: true
      - run:
        - name: Run script.sh
        - command: ./script.sh